# Generated by Django 3.2.5 on 2021-08-03 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='price',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
