# Generated by Django 3.2.5 on 2021-08-06 17:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.CharField(max_length=10)),
                ('b_p', models.CharField(max_length=10)),
                ('s_p', models.CharField(max_length=10)),
                ('bquantity', models.CharField(max_length=10)),
                ('squantity', models.CharField(max_length=10)),
                ('btime', models.CharField(max_length=10)),
                ('stime', models.CharField(max_length=10)),
                ('ordered_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
